<div class="col-12 m-0">
	<div class="input-group">
		<h4 class="m-0 pt-4">Conceptos</h4>
	</div>
</div>
<div class="col-12 m-0">
	<label for="autoSizingInput" class="mb-0 ">Concepto(s)</label>
	<div class="input-group">
		<div class="input-group-text">*</div>
		<?= Form::text(
		    'recibo.Concepto',
		    'class="form-control" 
			maxlength="100"
			placeholder="Concepto: [Renta, Estacionamiento, etc.], [Dirección de pago], [Mes a pagar], [Año]"  required'
		) ?>
	</div>
</div>

<div class="col-12 m-0">
	<label for="autoSizingInputGroup" class="mb-0 pt-3">Precio Unitario</label>
	<div class="input-group">
		<div class="input-group-text">*</div>
		<?= Form::number('recibo.PrecioUnitario', 'class="form-control" 
		maxlength="100"
		placeholder="[Numero sin decimales]"  required') ?>
	</div>
</div>