<div class="card-header" id="concepto">
	<h2 class="mb-0">
		<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse"
			data-target="#collapseTwoConcepto" aria-expanded="false" aria-controls="collapseTwoConcepto">
			<h4 class="m-0 pt-0">Concepto</h4>
		</button>
	</h2>
</div>
<div id="collapseTwoConcepto" class="collapse" aria-labelledby="concepto" data-parent="#accordionExample">
	<div class="card-body">

		<div class="col-12 m-0">
			<label for="autoSizingInput" class="mb-0 ">Concepto(s)</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text(
				    'recibo.Concepto',
				    'class="form-control" 
			maxlength="100"
			placeholder="[Renta, Estacionamiento, etc.], [Dirección de pago], [Mes a pagar], [Año]"  required'
				) ?>
			</div>
		</div>

		<div class="col-12 m-0">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Precio Unitario</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::number('recibo.PrecioUnitario', 'class="form-control" 
		maxlength="100"
		placeholder="[Numero sin decimales]"  required') ?>
			</div>
		</div>


	</div>
</div>