<div class="col-12 m-0">
	<div class="input-group">
		<h4 class="m-0 pt-4">Receptor</h4>
	</div>
	<div class=" alert alert-warning alert-dismissible fade show" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<strong>Los campos con * son obligatorios</strong>
	</div>

	<script>
		$(".alert").alert();
	</script>
</div>

<script>
	$(".alert").alert();
</script>
<div class="col-6 m-0">
	<label for="autoSizingInput">Nombre y Apellidos</label>
	<div class="input-group">
		<div class="input-group-text">*</div>
		<?= Form::text('recibo.ReceptorNombre', 'class="form-control"  required') ?>
	</div>
</div>