# Save as .codeclimate.yml (note leading .) in project root directory
# Excluded deprecated libs
languages:
  Ruby: false
  JavaScript: true
  PHP: true
exclude_paths:
- core/libs/db/*
- core/libs/kumbia_activerecord/*
- core/libs/acl/*