language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - master
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: master
    - php: 5.5

notifications:
# slack: kumbiaphp:51JaKQTXASwf52D8b32OyWb9
#    irc: "irc.freenode.org#kumbiaphp"
#    email:
#    - programador.manuel@gmail.com


# env:
#  - DB=mysql
#  - DB=pgsql
#  - DB=sqlite

script: 
  - phpunit --configuration core/phpunit.xml.dist --coverage-text --colors --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover