<div class="card mb-3">
	<div class="card-body">
		<h1>
			<?= "Historial de pagos y recibos " ?>
		</h1>
		<h3>
			<span
				class="text-primary"><?= "{$father->Nombre}"?></span>
			<span
				class="text-primary"><?= $father->propiedades->Direccion ?></span>
		</h3>

		<div class="row mb-3">

			<div class="actions col-12">
				<?= Html::link("arrendatarios", 'Volver', 'class="btn btn-danger btn-block"')?>
			</div>

		</div>

		<?php if (isset($data->items) && (count($data->items) > 0)) : ?>
		<div class="row">
			<div class="col-12 ">
				<table
					class="table w-100 d-block d-md-table text-center align-middle table-striped table-inverse table-responsive table-bordered table-hover">
					<thead class="thead-dark">
						<tr>
							<?php $headers = ['#','Total', 'Concepto', 'FechaHoraEmision', 'Estado', ''  ] ?>
							<?php foreach ($headers as $field) : ?>
							<th>
								<?= $field ?>
							</th>
							<?php endforeach?>
						</tr>
					</thead>

					<tbody>
						<?php foreach ($data->items as $i => $item) : ?>
						<tr>

							<?php foreach ($headers as $field) : ?>
							<td scope="row" class="align-middle">
								<?php if($field == 'Total'): ?>
								<?= h((new NumberFormatter("es-MEX", NumberFormatter::CURRENCY))->format($item->$field))?>
								<?php elseif($field === '#') : ?>
								<?= h($i + 1) ?>
								<?php elseif($field === 'Estado') : ?>
								<?php if($item->Pagado) : ?>
								<span class="badge badge-success text-center">
									<?= h('Pagado')?>
								</span>
								<?php else : ?>
								<span class="badge badge-warning text-center">
									<?= h('No Pagado')?>
								</span>
								<?php endif ?>

								<?php elseif($field === ''): ?>
								<div class="row m-1">

									<div class="desk-content col-md-4  p-0 ">
										<?= Html::linkAction(
										    "marcar/$father->Id/$item->Id/1",
										    '<i class="fa fa-check"></i>',
										    ' 
										 data-toggle="tooltip" data-placement="top" title="Marcar como pagado"
										 class="btn btn-primary btn-success btn-block" '
										) ?>
									</div>

									<div class="phone-content col-md-4  p-0 ">
										<?= Html::linkAction(
										    "marcar/$father->Id/$item->Id/1",
										    '<p class="m-0 text-success">Pagado</p>',
										) ?>
									</div>

									<div class="desk-content col-md-4  p-0 ">
										<?= Html::linkAction(
										    "historial/$item->Id",
										    '<i class="fa fa-download"></i>',
										    'onclick="UpdateAutoRecipe()" 
										 data-toggle="tooltip" data-placement="top" title="Descargar recibo"
										 class="btn btn-primary btn-primary btn-block" '
										) ?>
									</div>

									<div class="phone-content col-md-4  p-0 ">
										<?= Html::linkAction(
										    "historial/$item->Id",
										    '<p class="m-0 text-primary">Descargar</p>'
										) ?>
									</div>

									<div class="desk-content col-md-4  p-0 ">
										<?= Html::linkAction(
										    "marcar/$father->Id/$item->Id/0",
										    '<i class="fa fa-file-excel"></i>',
										    '
										 data-toggle="tooltip" data-placement="top" title="Marcar como adeudo"
										 class="btn btn-primary btn-danger btn-block" '
										) ?>
									</div>

									<div class="phone-content col-md-4  p-0 ">
										<?= Html::linkAction(
										    "marcar/$father->Id/$item->Id/0",
										    '<p class="m-0 text-danger">Adeudo</p>'
										) ?>
									</div>

									<?php else: ?>
									<?= h($item->$field) ?>
									<?php endif ?>
							</td>
							<?php endforeach?>


						</tr>
						<?php endforeach?>
					</tbody>
				</table>

				<?php View::partial('paginators/digg', false, array('page' => $data ,'url' => Router::get('controller_path').'/index')) ?>

				<?php else: ?>
				<p>No hay registros para mostrar</p>
			</div>

		</div>

		<?php endif ?>
	</div>
</div>