<div class="card mb-3">
	<div class="card-body">
		<h1>
			<?= ucwords("$model") ?>
		</h1>

		<div class="row mb-3">

			<div class="actions col-6">
				<?= Html::linkAction("crear/", 'Crear ', 'class="btn btn-primary btn-block"')?>
			</div>
			<div class="actions col-6">
				<?= Html::link("", 'Inicio', 'class="btn btn-danger btn-block"')?>
			</div>
		</div>

		<?php if (isset($data->items) && (count($data->items) > 0)) : ?>
		<div class="row">
			<div class="col-12">
				<table
					class="table w-100 d-block d-md-table text-center table-striped table-inverse table-responsive table-bordered table-hover">
					<thead class="thead-dark">
						<tr>
							<th></th>
							<?php foreach (current($data->items)->fields as $field) : ?>
							<?php if($field !== 'PrecioTexto' && $field !== 'Id'): ?>
							<th>
								<?= (current($data->items)->get_alias($field))?>
							</th>



							<?php endif ?>
							<?php endforeach?>
							<th>
								<?= h('Estado Pago')?>
							</th>
							<th></th>
						</tr>
					</thead>

					<thead>

					</thead>
					<tbody>
						<?php foreach ($data->items as $i => $item) : ?>
						<tr>
							<td><?= h($i + 1) ?></td>
							<?php foreach ($item->fields as $field) : ?>
							<?php if($field !== 'PrecioTexto' && $field !== 'Id'): ?>
							<td scope="row">
								<?php if($field == 'Precio'): ?>
								<?= h(( new NumberFormatter("es-MEX", NumberFormatter::CURRENCY) )->format($item->$field))?>

								<?php else: ?>
								<?php if($field == 'propiedades_id'): ?>
								<?= h($item->propiedades->Nombre)?>
								<?php else: ?>
								<?= h($item->$field)?>
								<?php endif ?>

								<?php endif ?>
							</td>
							<?php endif ?>
							<?php endforeach?>
							<td>
								<?php $len = sizeof($item->recibo) ?>
								<?php if($len > 0) :  ?>
								<?php $reciboFecha = (new DateTime($item->recibo[$len - 1]->FechaHoraEmision))->format('m') ?>
								<?php $fechaActual = (new DateTime())->format('m')  ?>

								<?php  if($reciboFecha === $fechaActual): ?>
								<span class="badge badge-success">
									<?= h('Pagado')?>
								</span>

								<?php elseif($fechaActual > $reciboFecha) : ?>
								<span class="badge badge-warning">
									<?= h('Por Pagar')?>
								</span>
								<?php endif ?>
								<?php else: ?>
								<span class="badge badge-secondary">
									<?= h('Sin Recibos')?>
								</span>
								<?php endif ?>

							</td>
							<td scope="row">
								<div class="row m-1">

									<div class="col-xs-12 col-md-5  p-0 m-1">
										<?= Html::linkAction("editar/$item->Id", '<i class="fa fa-edit"></i>', ' class="btn btn-primary btn-block" ') ?>
									</div>



									<div class="col-xs-12 col-md-5 p-0 m-1">

										<?= Html::linkAction(
										    "borrar/$item->Id",
										    '<i class="fa fa-trash"></i>',
										    'onclick="return confirm(\'Estas seguro?\')" class="btn btn-danger btn-block" '
										) ?>

									</div>

								</div>
							</td>

						</tr>
						<?php endforeach?>
					</tbody>
				</table>

				<?php View::partial('paginators/digg', false, array('page' => $data ,'url' => Router::get('controller_path').'/index')) ?>

				<?php else: ?>
				<p>No hay registros para mostrar</p>
			</div>

		</div>

		<?php endif ?>
	</div>
</div>