<div class="card mb-3">

	<div class="card-body">


		<?= View::partial('pollo/formularios/plantillas/titulo_controlador', null, ['titulo' => $controller_name])?>

		<div class="row">
			<?= View::partial('pollo/formularios/mensajes/obligatorio')?>
		</div>

		<?= Form::open('contratos/crearContrato') ?>

		<div class="accordion" id="accordionExample">
			<div class="card">
				<?= View::partial('pollo/formularios/contratos/arrendamiento/arrendatario')?>

				<?= View::partial('pollo/formularios/contratos/arrendamiento/fiador')?>

				<?= View::partial('pollo/formularios/contratos/arrendamiento/propiedad')?>
			</div>
		</div>

		<div class="row pt-4">
			<div class="col-6 ">
				<button type="submit" class="btn btn-primary btn-lg btn-block">Crear</button>
			</div>

			<div class="col-6 ">
				<button type="button" class="btn btn-danger btn-lg btn-block" onclick="clearInputs()">Limpiar</button>
			</div>
		</div>
		<?= Form::close() ?>
	</div>

</div>