<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
	<?= Html::link('index', "ContratoPollo", 'class="navbar-brand" ') ?>
	<button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
		aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
	<div class="collapse navbar-collapse" id="collapsibleNavId">
		<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
			<li class="nav-item ">
				<?= Html::link('contratos', "Contratos", 'class="nav-link"') ?>
			</li>
			<li class="nav-item">
				<?= Html::link('recibos', "Recibos", 'class="nav-link"') ?>
			</li>


		</ul>

	</div>
</nav>