<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
	<?= Html::link('index', "ContratoPollo", 'class="navbar-brand" ') ?>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
		aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
			<li class="nav-item ">
				<?= Html::link('contratos', "Contratos", 'class="nav-link"') ?>
			</li>
			<li class="nav-item">
				<?= Html::link('recibos', "Recibos", 'class="nav-link"') ?>
			</li>


		</ul>

	</div>
</nav>