<div class="card mb-3">
	<div class="card-body">
		<?= View::partial('pollo/formularios/plantillas/titulo_controlador', null, ['titulo' => $controller_name])?>
		<div class="row">
			<?= View::partial('pollo/formularios/mensajes/obligatorio')?>
		</div>

		<?= Form::open('recibos/crearRecibo') ?>

		<div class="accordion" id="accordionExample">
			<div class="card">
				<?= View::partial('pollo/formularios/recibos/receptor')?>

				<?= View::partial('pollo/formularios/recibos/conceptos')?>
			</div>
		</div>

		<?= View::partial('pollo/formularios/plantillas/botones_form')?>
		<?= Form::close() ?>
	</div>
</div>