<div class="card-header" id="fiador">
	<h2 class="mb-0">
		<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse"
			data-target="#collapseTwoFiador" aria-expanded="false" aria-controls="collapseTwoFiador">
			<h4 class="m-0 pt-0">Fiador</h4>
		</button>
	</h2>
</div>
<div id="collapseTwoFiador" class="collapse" aria-labelledby="fiador" data-parent="#accordionExample">
	<div class="card-body">

		<div class="col-auto m-0">
			<label for="autoSizingInput" class="mb-0 ">Nombre y Apellidos</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text('fiador.Nombre', 'class="form-control" maxlength="100" required') ?>
			</div>
		</div>

		<div class="col-auto m-0">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Direccion</label>
			<div class="input-group">
				<div class="input-group-text ">*</div>
				<?= Form::text('fiador.Direccion', 'class="form-control" maxlength="100"  placeholder="Direccion sin la palabra Calle" required') ?>
			</div>
		</div>

		<div class="col-auto m-0">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Colonia</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text('fiador.Colonia', 'class="form-control" maxlength="100" required') ?>
			</div>
		</div>

		<div class="col-auto m-0">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Municipio</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text('fiador.Municipio', 'class="form-control" maxlength="100" required') ?>
			</div>
		</div>

	</div>
</div>