<div class="card-header" id="headingTwo">
	<h2 class="mb-0">
		<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse"
			data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
			<h4 class="m-0 pt-0">Propiedades</h4>
		</button>
	</h2>
</div>
<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
	<div class="card-body">

		<div class="m-0 col-auto">
			<label for="autoSizingInput" class="mb-0">Precio por mes</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::number('propiedad.Precio', 'class="form-control" placeholder="Numero sin decimales"   required') ?>
			</div>
		</div>


		<div class="m-0 col-auto">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Direccion</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text('propiedad.Direccion', 'class="form-control" maxlength="100" required placeholder="Direccion sin la palabra Calle"') ?>
			</div>
		</div>

		<div class="m-0 col-auto">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Colonia</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text('propiedad.Colonia', 'class="form-control" maxlength="100" required') ?>
			</div>
		</div>

		<div class="m-0 col-auto">
			<label for="autoSizingInputGroup" class="mb-0 pt-3">Municipio</label>
			<div class="input-group">
				<div class="input-group-text">*</div>
				<?= Form::text('propiedad.Municipio', 'class="form-control" maxlength="100" required') ?>
			</div>
		</div>

	</div>
</div>