<div class="jumbotron">
	<h1 class="display-3">Bienvenido</h1>
	<p class="lead">Contrato Pollo Version Web, con webhook mejorado</p>
	<hr class="my-2">
	<p>En esta pagina podra generar contratos y recibos de manera automatica desde cualquier parte del mundo</p>

	<div class="row">

		<p class="lead col-6">
			<?= Html::link('contratos', "Generar contrato", 'class="btn btn-primary btn-lg btn-block"') ?>
		</p>
		<p class="lead col-6">
			<?= Html::link('recibos', "Generar Recibo", 'class="btn btn-success btn-lg btn-block"') ?>
			<?= Html::includeHeadLinks() ?>
		</p>
	</div>

</div>