<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset=<?= APP_CHARSET ?> >
	<title>Contrato-Pollo</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

</head>

<body>


	<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>


	<?= View::partial('pollo/navbar') ?>

	<div class="container-fluid mt-5">
		<?= View::content() ?>
	</div>



	<?= Tag::js('functions') ?>

</body>

</html>