<div class="card mb-3">
	<div class="card-body">


		<h2>
			<?= ucwords("$model"), " <span class = 'text-primary'>".  ucfirst($action_name) ."</span>" ?>
		</h2>

		<div class="row pt-3">
			<?= View::partial('pollo/formularios/mensajes/obligatorio')?>
		</div>

		<div class="col-12 p-0">
			<?php ModelForm::create($$model)?>
		</div>


		<?php //View::partial('editors/tinymce') // ya veremos si incluimos algun wysiwyg?>
	</div>
</div>