<div class="card mb-3">
	<div class="card-body">
		<h1>
			<?= ucwords("$model") ?>
		</h1>

		<div class="row mb-3">

			<div class="actions col-6">
				<?= Html::linkAction("crear/", 'Crear ', 'class="btn btn-primary btn-block"')?>
			</div>
			<div class="actions col-6">
				<?= Html::link("", 'Inicio', 'class="btn btn-danger btn-block"')?>
			</div>
		</div>

		<?php if (isset($data->items) && (count($data->items) > 0)) : ?>
		<div class="row">
			<div class="col-12">
				<table
					class="table w-100 d-block d-md-table  table-striped table-inverse table-responsive table-bordered table-hover">
					<thead class="thead-dark">
						<tr>
							<?php foreach (current($data->items)->fields as $field) : ?>
							<?php if($field !== 'PrecioTexto' && $field !== 'Id'): ?>
							<th>
								<?= (current($data->items)->get_alias($field))?>
							</th>
							<?php endif ?>
							<?php endforeach?>
							<th></th>
						</tr>
					</thead>

					<thead>

					</thead>
					<tbody>
						<?php foreach ($data->items as $item) : ?>
						<tr>
							<?php foreach ($item->fields as $field) : ?>
							<?php if($field !== 'PrecioTexto' && $field !== 'Id'): ?>
							<td scope="row">
								<?= h($item->$field)?>
							</td>
							<?php endif ?>
							<?php endforeach?>
							<td scope="row">
								<div class="row m-1">

									<div class="col-6 p-0">
										<a name="" id="" class="btn btn-primary btn-block"
											href="<?=  $controller_name . '/editar' . '/'. $item->Id ?>"
											role="button">
											<i class="fa fa-edit"></i>
										</a>
									</div>

									<div class="col-6 p-0">
										<a name="" id="" class="btn btn-danger btn-block"
											href="<?= $controller_name . '/borrar'. '/' . $item->Id ?>"
											role="button" onclick="return confirm('¿Está seguro?')">
											<i class="fa fa-trash"></i>
										</a>
									</div>

								</div>
							</td>
						</tr>
						<?php endforeach?>
					</tbody>
				</table>

				<?php View::partial('paginators/digg', false, array('page' => $data ,'url' => Router::get('controller_path').'/index')) ?>

				<?php else: ?>
				<p>No hay registros para mostrar</p>
			</div>

		</div>

		<?php endif ?>
	</div>
</div>